# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/winE/WorklSpace/Eclipse/SMRP2/UI/UI_matm.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 500)
        self.main_splitter = QtWidgets.QSplitter(Form)
        self.main_splitter.setGeometry(QtCore.QRect(20, 5, 866, 481))
        self.main_splitter.setOrientation(QtCore.Qt.Vertical)
        self.main_splitter.setHandleWidth(1)
        self.main_splitter.setObjectName("main_splitter")
        self.filter_frame = QtWidgets.QFrame(self.main_splitter)
        self.filter_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame.setObjectName("filter_frame")
        self.c_le_mat_no_filter = QtWidgets.QLineEdit(self.filter_frame)
        self.c_le_mat_no_filter.setGeometry(QtCore.QRect(60, 15, 96, 26))
        self.c_le_mat_no_filter.setObjectName("c_le_mat_no_filter")
        self.c_lb_mat_no_filter = QtWidgets.QLabel(self.filter_frame)
        self.c_lb_mat_no_filter.setGeometry(QtCore.QRect(5, 15, 66, 26))
        self.c_lb_mat_no_filter.setObjectName("c_lb_mat_no_filter")
        self.c_le_mat_nm_filter = QtWidgets.QLineEdit(self.filter_frame)
        self.c_le_mat_nm_filter.setGeometry(QtCore.QRect(255, 15, 431, 26))
        self.c_le_mat_nm_filter.setText("")
        self.c_le_mat_nm_filter.setObjectName("c_le_mat_nm_filter")
        self.c_lb_mat_nm_filter = QtWidgets.QLabel(self.filter_frame)
        self.c_lb_mat_nm_filter.setGeometry(QtCore.QRect(180, 15, 91, 26))
        self.c_lb_mat_nm_filter.setObjectName("c_lb_mat_nm_filter")
        self.hbox_splitter = QtWidgets.QSplitter(self.main_splitter)
        self.hbox_splitter.setLineWidth(0)
        self.hbox_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.hbox_splitter.setHandleWidth(0)
        self.hbox_splitter.setObjectName("hbox_splitter")
        self.c_tv_matm_filter = QtWidgets.QTableView(self.hbox_splitter)
        self.c_tv_matm_filter.setObjectName("c_tv_matm_filter")
        self.vbox_splitter = QtWidgets.QSplitter(self.hbox_splitter)
        self.vbox_splitter.setOrientation(QtCore.Qt.Vertical)
        self.vbox_splitter.setHandleWidth(0)
        self.vbox_splitter.setObjectName("vbox_splitter")
        self.main_frame = QtWidgets.QFrame(self.vbox_splitter)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(11)
        self.main_frame.setFont(font)
        self.main_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.c_le_mat_no = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_mat_no.setGeometry(QtCore.QRect(95, 15, 96, 26))
        self.c_le_mat_no.setObjectName("c_le_mat_no")
        self.c_lb_mat_no = QtWidgets.QLabel(self.main_frame)
        self.c_lb_mat_no.setGeometry(QtCore.QRect(30, 15, 66, 26))
        self.c_lb_mat_no.setObjectName("c_lb_mat_no")
        self.c_lb_color_no = QtWidgets.QLabel(self.main_frame)
        self.c_lb_color_no.setGeometry(QtCore.QRect(205, 15, 66, 26))
        self.c_lb_color_no.setObjectName("c_lb_color_no")
        self.c_le_color_no = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_color_no.setGeometry(QtCore.QRect(270, 15, 96, 26))
        self.c_le_color_no.setObjectName("c_le_color_no")
        self.c_lb_color_nm = QtWidgets.QLabel(self.main_frame)
        self.c_lb_color_nm.setGeometry(QtCore.QRect(370, 15, 156, 26))
        self.c_lb_color_nm.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.c_lb_color_nm.setObjectName("c_lb_color_nm")
        self.c_lb_mat_nm = QtWidgets.QLabel(self.main_frame)
        self.c_lb_mat_nm.setGeometry(QtCore.QRect(5, 45, 91, 26))
        self.c_lb_mat_nm.setObjectName("c_lb_mat_nm")
        self.c_le_mat_nm = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_mat_nm.setGeometry(QtCore.QRect(95, 45, 431, 56))
        self.c_le_mat_nm.setText("")
        self.c_le_mat_nm.setObjectName("c_le_mat_nm")
        self.c_lb_mat_nm_en = QtWidgets.QLabel(self.main_frame)
        self.c_lb_mat_nm_en.setGeometry(QtCore.QRect(65, 105, 36, 26))
        self.c_lb_mat_nm_en.setObjectName("c_lb_mat_nm_en")
        self.c_le_mat_nm_en = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_mat_nm_en.setGeometry(QtCore.QRect(95, 105, 431, 56))
        self.c_le_mat_nm_en.setObjectName("c_le_mat_nm_en")
        self.c_lb_kindd_nm = QtWidgets.QLabel(self.main_frame)
        self.c_lb_kindd_nm.setGeometry(QtCore.QRect(30, 165, 66, 26))
        self.c_lb_kindd_nm.setObjectName("c_lb_kindd_nm")
        self.c_le_kindd_nm = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_kindd_nm.setGeometry(QtCore.QRect(95, 165, 66, 26))
        self.c_le_kindd_nm.setObjectName("c_le_kindd_nm")
        self.c_lb_process_mk = QtWidgets.QLabel(self.main_frame)
        self.c_lb_process_mk.setGeometry(QtCore.QRect(220, 165, 66, 26))
        self.c_lb_process_mk.setObjectName("c_lb_process_mk")
        self.c_le_process_mk = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_process_mk.setGeometry(QtCore.QRect(285, 165, 66, 26))
        self.c_le_process_mk.setObjectName("c_le_process_mk")
        self.c_lb_exceed_rec_mk = QtWidgets.QLabel(self.main_frame)
        self.c_lb_exceed_rec_mk.setGeometry(QtCore.QRect(395, 165, 66, 26))
        self.c_lb_exceed_rec_mk.setObjectName("c_lb_exceed_rec_mk")
        self.c_le_exceed_rec_mk = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_exceed_rec_mk.setGeometry(QtCore.QRect(460, 165, 21, 26))
        self.c_le_exceed_rec_mk.setObjectName("c_le_exceed_rec_mk")
        self.c_lb_onway_qty = QtWidgets.QLabel(self.main_frame)
        self.c_lb_onway_qty.setGeometry(QtCore.QRect(45, 195, 51, 26))
        self.c_lb_onway_qty.setObjectName("c_lb_onway_qty")
        self.c_le_onway_qty = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_onway_qty.setGeometry(QtCore.QRect(95, 195, 96, 26))
        self.c_le_onway_qty.setInputMask("")
        self.c_le_onway_qty.setObjectName("c_le_onway_qty")
        self.c_le_safestk_qty = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_safestk_qty.setGeometry(QtCore.QRect(285, 195, 101, 26))
        self.c_le_safestk_qty.setInputMask("")
        self.c_le_safestk_qty.setObjectName("c_le_safestk_qty")
        self.c_lb_safestk_qty = QtWidgets.QLabel(self.main_frame)
        self.c_lb_safestk_qty.setGeometry(QtCore.QRect(220, 195, 66, 26))
        self.c_lb_safestk_qty.setObjectName("c_lb_safestk_qty")
        self.c_le_purchase_day = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_purchase_day.setGeometry(QtCore.QRect(460, 195, 31, 26))
        self.c_le_purchase_day.setInputMask("")
        self.c_le_purchase_day.setObjectName("c_le_purchase_day")
        self.c_lb_purchase_day = QtWidgets.QLabel(self.main_frame)
        self.c_lb_purchase_day.setGeometry(QtCore.QRect(410, 195, 51, 26))
        self.c_lb_purchase_day.setObjectName("c_lb_purchase_day")
        self.c_le_unit_price = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_unit_price.setGeometry(QtCore.QRect(95, 225, 101, 26))
        self.c_le_unit_price.setInputMask("")
        self.c_le_unit_price.setObjectName("c_le_unit_price")
        self.c_lb_unit_price = QtWidgets.QLabel(self.main_frame)
        self.c_lb_unit_price.setGeometry(QtCore.QRect(60, 225, 36, 26))
        self.c_lb_unit_price.setObjectName("c_lb_unit_price")
        self.c_lb_stop_user = QtWidgets.QLabel(self.main_frame)
        self.c_lb_stop_user.setGeometry(QtCore.QRect(235, 225, 51, 26))
        self.c_lb_stop_user.setObjectName("c_lb_stop_user")
        self.c_le_stop_user = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_stop_user.setGeometry(QtCore.QRect(285, 225, 101, 26))
        self.c_le_stop_user.setInputMask("")
        self.c_le_stop_user.setText("")
        self.c_le_stop_user.setObjectName("c_le_stop_user")
        self.c_lb_stop_date = QtWidgets.QLabel(self.main_frame)
        self.c_lb_stop_date.setGeometry(QtCore.QRect(395, 225, 66, 26))
        self.c_lb_stop_date.setObjectName("c_lb_stop_date")
        self.c_le_stop_date = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_stop_date.setGeometry(QtCore.QRect(460, 225, 71, 26))
        self.c_le_stop_date.setInputMask("")
        self.c_le_stop_date.setObjectName("c_le_stop_date")
        self.c_lb_modify_user = QtWidgets.QLabel(self.main_frame)
        self.c_lb_modify_user.setGeometry(QtCore.QRect(45, 255, 51, 26))
        self.c_lb_modify_user.setObjectName("c_lb_modify_user")
        self.c_le_modify_user = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_modify_user.setGeometry(QtCore.QRect(95, 255, 101, 26))
        self.c_le_modify_user.setInputMask("")
        self.c_le_modify_user.setText("")
        self.c_le_modify_user.setObjectName("c_le_modify_user")
        self.c_lb_modify_dt = QtWidgets.QLabel(self.main_frame)
        self.c_lb_modify_dt.setGeometry(QtCore.QRect(220, 255, 66, 26))
        self.c_lb_modify_dt.setObjectName("c_lb_modify_dt")
        self.c_le_modify_dt = QtWidgets.QLineEdit(self.main_frame)
        self.c_le_modify_dt.setGeometry(QtCore.QRect(285, 255, 71, 26))
        self.c_le_modify_dt.setInputMask("")
        self.c_le_modify_dt.setText("")
        self.c_le_modify_dt.setObjectName("c_le_modify_dt")
        self.c_tv_matvendorm = QtWidgets.QTableView(self.vbox_splitter)
        self.c_tv_matvendorm.setObjectName("c_tv_matvendorm")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.hbox_splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.pb_vbox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.pb_vbox.setContentsMargins(0, 0, 0, 0)
        self.pb_vbox.setSpacing(2)
        self.pb_vbox.setObjectName("pb_vbox")
        self.c_pb_append = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.c_pb_append.setObjectName("c_pb_append")
        self.pb_vbox.addWidget(self.c_pb_append)
        self.c_pb_edit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.c_pb_edit.setObjectName("c_pb_edit")
        self.pb_vbox.addWidget(self.c_pb_edit)
        self.c_pb_delete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.c_pb_delete.setObjectName("c_pb_delete")
        self.pb_vbox.addWidget(self.c_pb_delete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.pb_vbox.addItem(spacerItem)
        self.c_pb_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.c_pb_save.setObjectName("c_pb_save")
        self.pb_vbox.addWidget(self.c_pb_save)
        self.c_pb_quit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.c_pb_quit.setObjectName("c_pb_quit")
        self.pb_vbox.addWidget(self.c_pb_quit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.c_le_mat_no_filter.setText(_translate("Form", "ABCDEFGHIJ"))
        self.c_lb_mat_no_filter.setText(_translate("Form", "材料編號:"))
        self.c_lb_mat_nm_filter.setText(_translate("Form", "材料名稱(中):"))
        self.c_le_mat_no.setText(_translate("Form", "ABCDEFGHIJ"))
        self.c_lb_mat_no.setText(_translate("Form", "材料編號:"))
        self.c_lb_color_no.setText(_translate("Form", "顏色編號:"))
        self.c_le_color_no.setText(_translate("Form", "ABCDEFGHIJ"))
        self.c_lb_color_nm.setText(_translate("Form", "顏色名稱"))
        self.c_lb_mat_nm.setText(_translate("Form", "材料名稱(中):"))
        self.c_lb_mat_nm_en.setText(_translate("Form", "(英):"))
        self.c_lb_kindd_nm.setText(_translate("Form", "單位名稱:"))
        self.c_lb_process_mk.setText(_translate("Form", "加工材料:"))
        self.c_lb_exceed_rec_mk.setText(_translate("Form", "超交允收:"))
        self.c_le_exceed_rec_mk.setText(_translate("Form", "Y"))
        self.c_lb_onway_qty.setText(_translate("Form", "在途量:"))
        self.c_le_onway_qty.setText(_translate("Form", "999,999,999.99"))
        self.c_le_safestk_qty.setText(_translate("Form", "999,999,999.99"))
        self.c_lb_safestk_qty.setText(_translate("Form", "安全存量:"))
        self.c_le_purchase_day.setText(_translate("Form", "999"))
        self.c_lb_purchase_day.setText(_translate("Form", "購備期:"))
        self.c_le_unit_price.setText(_translate("Form", "999,999.9999"))
        self.c_lb_unit_price.setText(_translate("Form", "單價:"))
        self.c_lb_stop_user.setText(_translate("Form", "停用人:"))
        self.c_lb_stop_date.setText(_translate("Form", "停用日期:"))
        self.c_le_stop_date.setText(_translate("Form", "2017/01/20"))
        self.c_lb_modify_user.setText(_translate("Form", "異動人:"))
        self.c_lb_modify_dt.setText(_translate("Form", "異動日期:"))
        self.c_pb_append.setText(_translate("Form", "新增"))
        self.c_pb_edit.setText(_translate("Form", "修改"))
        self.c_pb_delete.setText(_translate("Form", "刪除"))
        self.c_pb_save.setText(_translate("Form", "儲存"))
        self.c_pb_quit.setText(_translate("Form", "離開"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

